# Generated by Django 3.2.9 on 2021-12-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=155)),
                ('units_sold', models.CharField(max_length=155)),
                ('in_stock', models.CharField(max_length=155)),
                ('expire_date', models.CharField(max_length=155)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
