# Generated by Django 3.2.9 on 2021-12-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211209_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductItem',
        ),
    ]
