# Generated by Django 3.2.9 on 2021-12-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_productitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product'),
        ),
    ]
