# Generated by Django 3.2.9 on 2021-12-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productitem_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='is_delete',
        ),
    ]
